name=ERNI
version=1.1.0
author=OPT-OUT
maintainer=OPT-OUT
sentence=ESP-NOW Reticulum Network Interface.
paragraph=A stripped-down, ultra-high-speed C++ bridge that effectively converts ESP-NOW hardware into a physical layer for the Reticulum Network Stack (RNS).
category=Communication
url=https://github.com/0P7-0U7/ERNI
architectures=esp32
includes=src/ERNI_Framing.h,src/ERNI_Mesh.h
